#!/bin/sh
if test $# -gt 0; then
	for arg
	do
		case "$arg" in
			--dev)
                                ./bin/gnu/CogVM shared/Pharo2.0.image
			;;
			--version)
                                ./bin/gnu/CogVM shared/Pharo2.0.image --version
			;;
			--debug)
                                ./bin/gnu/CogVM -vm-display-null shared/Pharo2.0.image --debug
			;;
			*)
				echo "Usage"
				echo "====="
				echo "Debug mode:		$0 [--debug]"
				echo "Development mode:	$0 [--dev]"
				echo "Query version:	$0 [--version]"
			;;
		esac
	done
else
                ./bin/gnu/CogVM -vm-display-null shared/Pharo2.0.image --serve
fi
