#!/bin/sh
if test $# -gt 0; then
	for arg
	do
		case "$arg" in
			--dev)
                                bin/gnu/CogVM shared/Pharo2.0.image
			;;
			--debug)
                                bin/gnu/CogVM -vm-display-null shared/Pharo2.0.image --debug
			;;
			*)
				echo "Usage: $0 [--debug]"
			;;
		esac
	done
else
                bin/gnu/CogVM -vm-display-null shared/Pharo2.0.image --serve
fi
