#!/bin/sh

BASEDIR=$(dirname $0)

# Find libudev.so.0 for node-webkit
if ! test -h libudev.so.0; then
    if test -e /lib/x86_64-linux-gnu/libudev.so.1; then
        ln -s /lib/x86_64-linux-gnu/libudev.so.1 $BASEDIR/libudev.so.0
    elif test -e /opt/google/chrome/libudev.so.0; then
        ln -s /opt/google/chrome/libudev.so.0 $BASEDIR/libudev.so.0
    else
        echo "Didn't find libudev.so.1 or libudev.so.0. Please provide a link."
        echo "Also consider providing a patch to the Snap4Arduino project to help other users."
        exit 1
    fi
fi

LD_LIBRARY_PATH=$BASEDIR $BASEDIR/nw $BASEDIR/app.nw
